/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/dreams": {
    get: operations["index"];
  };
  "/dreams/{id}": {
    get: operations["one"];
  };
  "/hello": {
    get: operations["index_1"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    DreamDto: {
      /** Format: int64 */
      id: number;
      title: string;
      description: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  index: {
    responses: {
      /** @description index 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["DreamDto"][];
        };
      };
    };
  };
  one: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description one 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["DreamDto"];
        };
      };
    };
  };
  index_1: {
    responses: {
      /** @description index_1 200 response */
      200: {
        content: {
          "text/plain": string;
        };
      };
    };
  };
}
