/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/dreams": {
    get: operations["index"];
    post: operations["create"];
  };
  "/dreams/{id}": {
    get: operations["one"];
    delete: operations["delete"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    DreamDto: {
      /** Format: int64 */
      id: number;
      /** Format: date */
      date: string;
      title: string;
      draft: string;
      description: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  index: {
    responses: {
      /** @description index 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["DreamDto"][];
        };
      };
    };
  };
  create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DreamDto"];
      };
    };
    responses: {
      /** @description create 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["DreamDto"];
        };
      };
    };
  };
  one: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description one 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["DreamDto"];
        };
      };
    };
  };
  delete: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description delete 200 response */
      200: {
        content: never;
      };
    };
  };
}
